let HttpMessages={
    internalErrorMsg: "Somthing goes wrong, Try after somtime",
    paramsMissingMsg: 'Request paramas missing',
    authUserNotFound: 'Authentication failed. User not found',
    invalidAccountDetail: 'Invalid account detail',
    authFailed: 'Authentication failed. Wrong Password',
    profileUpdatedSuccessfully:'Profile updated successfully',
    profileRemoveSuccessfully:'Profile photo remove successfully',
    vehiclePhotoRemoveSuccessfully:'Vehicle photo remove successfully',
    vehicleRemoveSuccessfully:'Vehicle remove successfully',
    vehicleBrandRemoveSuccessfully:'Vehicle Brand remove successfully',
    vehicleServiceRemoveSuccessfully:'Vehicle service remove successfully',
    vehicleNotFound:'Vehicle not found',
    vehicleBrandNotFound:'Brand not found',
    vehicleServiceNotFound:'Service not found',
    invalidEmail:'Invalid email address',
    passwordCodeMessage:"Verificatin code send on mobile",
    passwordCodeVerificationSuccess:"Code verification success",
    forgotPasswordCodeNotVerified:"Verificatin code not verified",
    passwordChangeSuccessFully:"Password change successfully",
    passwordChangeError:"Password not matched",
    emailSent:"Code Sent on your register email",
    actionSuccessfully:'Recored updated successfully',
    listingFounded:'Listing founded',
    biilAddressNotFounded:'BillingAddressId not founded',
    requestNotFound:'Request value not founded',
    recordedNotfound:"Record Not found",
    recordedAdded:"Record Added Successfully",
    recoredFound:"Record Founded",
    recoredDeleted:"Record Deleted",
    recoredUpdateed:"Record Updated Successfully",
    usernameAlreadyExist:"This username already exists",
    mobileAlreadyExist:"This mobile already exists",
    usernameAvailable:"This username available",
    loginAvailable:"Mobile login available",
    mobileVerified:"Mobile login verified"
    
}

module.exports=HttpMessages